services:
  cf_analyser_dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/code
    container_name: cf_analyser_dev
  sel:
    image: "selenium/standalone-firefox"
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    container_name: sel
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pwd
      POSTGRES_DB: exampledb
    container_name: db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080