services:
  cf_analyser_dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/code
    container_name: cf_analyser_dev
  sel:
    image: "selenium/standalone-firefox"
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    container_name: sel