apiVersion: v1
kind: Service
metadata:
  name: sel
spec:
  selector:
    app: selenium
  ports:
    - name: connectionforwebdriver
      protocol: TCP
      port: 4444
      targetPort: 4444
  type: ClusterIP
