apiVersion: v1
kind: Service
metadata:
  name: sel-external
spec:
  selector:
    app: selenium
  ports:
    - name: selenium-external
      protocol: TCP
      port: 5900
      targetPort: 5900
      nodePort: 30171
  type: NodePort