apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.selenium_svc_external.name }}
spec:
  selector:
    app: {{ .Values.app.selenium.name }}
  ports:
    - name: selenium-external
      protocol: TCP
      port: {{ .Values.app.selenium_svc_external.port }}
      targetPort: {{ .Values.app.selenium.port_external }}
      nodePort: {{ .Values.app.selenium_svc_external.nodePortkub }}
  type: NodePort