apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.selenium_svc_internal.name }}
spec:
  selector:
    app: {{ .Values.app.selenium.name }}
  ports:
    - name: connectionforwebdriver
      protocol: TCP
      port: {{ .Values.app.selenium_svc_internal.port }}
      targetPort: {{ .Values.app.selenium.port_internal }}
  type: ClusterIP
