app:
  name: cfanalyser
  cfanalyser:
    name: cf-analyser
    image: tamasujvari/cfanalyser:test_debug
    replicas: 1
  selenium:
    name: selenium
    image: selenium/standalone-firefox:123.0
    port_internal: 4444
    port_external: 7900
  selenium_svc_internal:
    name: selenium-svc
    port: 4444
  selenium_svc_external:
    name: sel-external
    port: 7900
    nodePort: 30171
